### ISSUE TITLE
if quota is exceeded, the app CRASHES - should throw an error

### ISSUE THREAD

**Issue by OhadR** [bigdatacloudapi/nodejs-api-client#1]
i use the nodejs client. I try to call reverseGeocode. it works perfect until the quota has exceeded. since then, when I try to invoke the call, the client crashes my app.

i would expect an error to be thrown.

**Comment by bigdatacloud-cam** [comment]
Please wrap any synchronous (await) calls in a try/catch statement and ensure to utilize the ` .then().catch()` promise functionality when used asynchronously.

We have tested this issue in-house with quota-exceeded credentials and were unable to replicate any application crashes when exceptions are handled correctly.

It is worth noting that an issue such as incorrect/missing/invalid/exceeded API credentials will trigger an exception/promise-rejection with a JSON object detailing the issue and the HTTP status code of the response, such as 403.

The README has been updated with additional information to outline promise exception handling.

If you are still experiencing this problem with the latest version of this module, please submit a new issue with some additional information, such as example code and exception output.
